export const SET_FILTER_DATA = 'CATALOG/SET_FILTER_DATA';
export const SET_ACTIVE_CATEGORY = 'CATALOG/SET_ACTIVE_CATEGORY';
export const APPEND_FILTER_DATA = 'CATALOG/APPEND_FILTER_DATA';
export const SET_HAS_MORE = 'CATALOG/SET_HAS_MORE';
export const SET_LOADING = 'CATALOG/SET_LOADING';
export const SET_SEARCH_QUERY = 'CATALOG/SET_SEARCH_QUERY';
export const SET_CURRENT_PAGE = 'CATALOG/SET_CURRENT_PAGE';
